### ISSUE TITLE
Error while using in Rails 5

### ISSUE THREAD

**Issue by Zsavajji** [toy/image_optim_rails#2]
Hi, 
i installed the gem as documented, and provided configuration, but when i include an image the following error gets produced: 
`undefined method 'call' for :image_optim:Symbol`

Is the gem not compatible with sprockets 4? 

Thank you!

**Comment by toy** [comment]
Thanks for reporting, I'll look into that

**Comment by Zsavajji** [comment]
Whoops, not solved, just made a mistake :D 
Thank you for checking it out!

**Comment by toy** [comment]
API change in sprockets, please check if branch [sprockets4](/toy/image_optim_rails/tree/sprockets4) works for you.

**Comment by Zsavajji** [comment]
Will do tomorrow and report back, thanks!

**Comment by Zsavajji** [comment]
Yes, it works correctly in my Rails 5.1 application, thank you!

**Comment by toy** [comment]
Just released v0.3.0
